language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk11

cache:
  directories:
    - .autoconf
    - "$HOME/.m2"

after_success:
  - mvn coveralls:report

notifications:
  email: false

# whitelist
branches:
  only:
    - master

env:
  global:
    - secure: nMIGJAoGBALeFvpaS4szqW9jo3uH3kaS2YJZSyghvokomKuiPIBr8mnO6BNm6C5sJ\nDKX7ihhJdKUA/MpEFCiObj5ZPiXcV7gHlyVN2FCP5ucFLHtasa3j6nCH5lvdLxAw\nAbPKq8PPCq8rurmFWBLuuCWXR0VW2OG1+Oo4b9U1d5ywST7hpvOrAgMBAAE=