language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk11

cache:
  directories:
    - .autoconf
    - "$HOME/.m2"

after_success:
  - mvn coveralls:report

notifications:
  email: false

# whitelist
branches:
  only:
    - master
